apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service-gin-deployment
  labels:
    app: web-service-gin
  annotations:
    linkerd.io/inject: "disabled"    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-service-gin
  template:
    metadata:
      labels:
        app: web-service-gin
    spec:
      imagePullSecrets:
        - name: sg185141reg      
      containers:
        - name: web-service-gin
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent          
          ports:
          - containerPort: 8080
            name: metrics
