apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service-gin-deployment
  labels:
    app: web-service-gin
  annotations:
    linkerd.io/inject: "disabled"    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-service-gin
  template:
    metadata:
      labels:
        app: web-service-gin
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"  # Replace with your application's port
      prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
        - name: sgreg      
      containers:
        - name: web-service-gin
          image: ghcr.io/sg185141_ncrvoyix/web-service-gin:latest
          ports:
          - containerPort: 8080
