apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: web-service-gin
  namespace: emissary
spec:
  port: 8080
  podSelector:
    matchLabels: {} # every pod
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: web-service-gin-auth
  namespace: emissary
spec:
  client:
    unauthenticated: true
  server:
    name: web-service-gin
