apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: ingress-key
  name: web-service-gin-ingress
  namespace: emissary
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mqtt
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    profile: main
    service: ambassador
  sessionAffinity: None
  type: LoadBalancer
