apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: listener-web-server
  namespace: emissary
spec:
  hostBinding:
    namespace:
      from: ALL
  port: 8080
  protocolStack:
  - TCP
  securityModel: INSECURE