apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: web-service-gin-server
spec:
  port: 8080
  podSelector:
    matchLabels: {} # every pod
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: web-service-gin-server-auth
spec:
  client:
    unauthenticated: true
  server:
    name: web-service-gin-server
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: web-service-gin
spec:
  port: 8080
  podSelector:
    matchLabels: {} # every pod
  proxyProtocol: opaque
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: web-service-gin-auth
spec:
  client:
    unauthenticated: true
  server:
    name: web-service-gin