apiVersion: v1
kind: Service
metadata:
  name: web-service-gin
spec:
  selector:
    app: web-service-gin-selector
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080