apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    virtualmachine.ncr.com/name: {{ .Release.Name }}
    virtualmachine.ncr.com/version: {{ .Chart.Version }}
    virtualmachine.ncr.com/created: {{ now | date "2006-01-02T15:04:05" }}
  labels:
    kubevirt.io/domain: {{ .Release.Name }}
