apiVersion: apps/v1
kind: Deployment
metadata:
  name: vxfuel-deployment
  labels:
    app: vxfuel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vxfuel
  template:
    metadata:
      labels:
        app: vxfuel
    spec:
      hostname: panther2
      volumes:
      - name: vxfuel-persist
        hostPath:
          path: /tmp/persist
          type: Directory
      containers:
      - name: vxfuel
        image: yocto-base
        volumeMounts:
        - name: vxfuel-persist
          mountPath: /persist/


#        ports:
#        - containerPort: 80
