apiVersion: apps/v1
kind: Deployment
metadata:
  name: vxfuel-deployment
  labels:
    app: vxfuel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vxfuel
  template:
    metadata:
      labels:
        app: vxfuel
    spec:
      hostname: panther2
      containers:
      - name: vxfuel
      volumeMounts:
      - name: vxfuel-persist
        mountPath: /persist/
        image: localhost:5001/vxfuel:latest
