apiVersion: v1
entries:
  vxfuel:
  - apiVersion: v2
    appVersion: 0.1.12
    created: "2024-03-14T14:54:24.163477129-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 526ca3c1f18e217781f887492f6f70ef7245c26f4b89e19157371ddc8876c585
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.12.tgz
    version: 0.1.12
  - apiVersion: v2
    appVersion: 0.1.11
    created: "2024-03-14T14:54:24.163349927-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 8ce28dc8f59596362f95a3632638d0418fd0c3045ad7ba9bdb2e725e02f3d073
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.11.tgz
    version: 0.1.11
  - apiVersion: v2
    appVersion: 0.1.10
    created: "2024-03-14T14:54:24.163105135-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 98fb56fc897e4c4ecb91314041d801f6285bf9e349e32b938bc72b8c6f27aea9
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v2
    appVersion: 0.1.9
    created: "2024-03-14T14:54:24.164872724-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: c11b595b67eae1d5a2714cbed7458d0c26b126d3135f3c17aeba1360ff3715e8
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 0.1.8
    created: "2024-03-14T14:54:24.164647108-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 69a9b53f50099547f6e32f80d3c05fb30a65ee9c7c1cc4acd1d93cd8e742d63d
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 0.1.7
    created: "2024-03-14T14:54:24.164438402-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 37e9f7b41ac4328bb065f19b0cba282b3ea71d27bf301818dcc12220a2b1da19
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 0.1.6
    created: "2024-03-14T14:54:24.16424794-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 08e2209a6d17bb0bf1031302b3c7ab50bec86232cb6db241d7f1fb593098c6d4
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2024-03-14T14:54:24.164025411-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: c1f7b125ad0cd32c39cee1c43a7adc9deb6ba3ebec5e072eea62c59e7163afa2
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2024-03-14T14:54:24.163801379-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 934110ef5243303ed4079cd4d348a79a83990f644b1e3975423918e04a6ffb82
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2024-03-14T14:54:24.163693042-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: dde22d1e491a287634bb398824e86e9613d120b640fea5da4900f8e795866aea
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.2.tgz
    version: 0.1.2
generated: "2024-03-14T14:54:24.156857524-04:00"
