apiVersion: v1
entries:
  vxfuel:
  - annotations:
      managed-by: ncr
    apiVersion: v2
    appVersion: 0.1.26
    created: "2024-03-26T13:17:31.576081565-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: a3ca5f907cffe11f0d6c6cd33edd67a5e0fa2f7e9cb9f7f32b85fd97a85082d4
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.26.tgz
    version: 0.1.26
  - annotations:
      managed-by: ncr
    apiVersion: v2
    appVersion: 0.1.25
    created: "2024-03-26T13:17:31.575944393-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: aaff46936cb337f6b275e5ef31957142b2f809e1256ef8d24a84f3552a7693c8
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.25.tgz
    version: 0.1.25
  - annotations:
      managed-by: ncr
    apiVersion: v2
    appVersion: 0.1.24
    created: "2024-03-26T13:17:31.575826437-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 38ebd0d429017a2a52c18934ab6b3dc764a26682aefee0320c764107e6232dfd
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.24.tgz
    version: 0.1.24
  - annotations:
      managed-by: ncr
    apiVersion: v2
    appVersion: 0.1.23
    created: "2024-03-26T13:17:31.575712189-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 62b229733e147dfd7893d9286beafb0053cee115692c69811c3bdc14a4986b81
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.23.tgz
    version: 0.1.23
  - annotations:
      managed-by: ncr
    apiVersion: v2
    appVersion: 0.1.22
    created: "2024-03-26T13:17:31.575587-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 1d1f7d4884da5ebf59845345939500a36a00f3103048343dae58efbd6eab9223
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.22.tgz
    version: 0.1.22
  - annotations:
      managed-by: ncr
    apiVersion: v2
    appVersion: 0.1.21
    created: "2024-03-26T13:17:31.575464516-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 78668f161252fb80e1b4529801cf1682d7634cef02de0d7a460fe03f69b78b86
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.21.tgz
    version: 0.1.21
  - annotations:
      managed-by: ncr
    apiVersion: v2
    appVersion: 0.1.20
    created: "2024-03-26T13:17:31.575318808-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 673aa3b6a1e52a4061e192e52e344cd08ebdb7f5d95ad732b65672dbd382a8a2
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.20.tgz
    version: 0.1.20
  - annotations:
      managed-by: ncr
    apiVersion: v2
    appVersion: 0.1.19
    created: "2024-03-26T13:17:31.575049924-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 507f4f8512d5b1142fc43fb39c8da0108241dc943521aad1c8d714d4dcfcae1f
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.19.tgz
    version: 0.1.19
  - annotations:
      managed-by: ncr
    apiVersion: v2
    appVersion: 0.1.18
    created: "2024-03-26T13:17:31.574897483-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 9e6f790b9ef08cf52b064eb99a1a76baedd53ee43011727c17d02845f9313ca4
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.18.tgz
    version: 0.1.18
  - annotations:
      managed-by: ncr
    apiVersion: v2
    appVersion: 0.1.17
    created: "2024-03-26T13:17:31.574781732-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: f8b5d19b4f23a0447fcff7b518e54d59426bd926faf51717c29f6072ec3ad4d2
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.17.tgz
    version: 0.1.17
  - annotations:
      managed-by: ncr
    apiVersion: v2
    appVersion: 0.1.16
    created: "2024-03-26T13:17:31.574666652-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 92be8f38a6aa6ba13a345f6e9397101addfda4ba21b1714efc3e29d3c561f845
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.16.tgz
    version: 0.1.16
  - annotations:
      managed-by: ncr
    apiVersion: v2
    appVersion: 0.1.15
    created: "2024-03-26T13:17:31.574553296-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: fd71348dc568dfc93abc35450efb2536774bb9248b63b645473cbfb8cffe7121
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.15.tgz
    version: 0.1.15
  - annotations:
      managed-by: ncr
    apiVersion: v2
    appVersion: 0.1.14
    created: "2024-03-26T13:17:31.574413429-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: a71b8e75908f900c2b268c709b0ae5b72e33152caaf38f3b8575ed39e56f93e0
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.14.tgz
    version: 0.1.14
  - apiVersion: v2
    appVersion: 0.1.12
    created: "2024-03-26T13:17:31.57426232-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 526ca3c1f18e217781f887492f6f70ef7245c26f4b89e19157371ddc8876c585
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.12.tgz
    version: 0.1.12
  - apiVersion: v2
    appVersion: 0.1.11
    created: "2024-03-26T13:17:31.574144195-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 8ce28dc8f59596362f95a3632638d0418fd0c3045ad7ba9bdb2e725e02f3d073
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.11.tgz
    version: 0.1.11
  - apiVersion: v2
    appVersion: 0.1.10
    created: "2024-03-26T13:17:31.574024466-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 98fb56fc897e4c4ecb91314041d801f6285bf9e349e32b938bc72b8c6f27aea9
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v2
    appVersion: 0.1.9
    created: "2024-03-26T13:17:31.576705416-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: c11b595b67eae1d5a2714cbed7458d0c26b126d3135f3c17aeba1360ff3715e8
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 0.1.8
    created: "2024-03-26T13:17:31.576582872-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 69a9b53f50099547f6e32f80d3c05fb30a65ee9c7c1cc4acd1d93cd8e742d63d
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 0.1.7
    created: "2024-03-26T13:17:31.576460919-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 37e9f7b41ac4328bb065f19b0cba282b3ea71d27bf301818dcc12220a2b1da19
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 0.1.6
    created: "2024-03-26T13:17:31.576368863-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 08e2209a6d17bb0bf1031302b3c7ab50bec86232cb6db241d7f1fb593098c6d4
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2024-03-26T13:17:31.576267409-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: c1f7b125ad0cd32c39cee1c43a7adc9deb6ba3ebec5e072eea62c59e7163afa2
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2024-03-26T13:17:31.576177768-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: 934110ef5243303ed4079cd4d348a79a83990f644b1e3975423918e04a6ffb82
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2024-03-26T13:17:31.575171256-04:00"
    description: vxFuel Helm chart for Kubernetes
    digest: dde22d1e491a287634bb398824e86e9613d120b640fea5da4900f8e795866aea
    name: vxfuel
    type: application
    urls:
    - docs/vxfuel-0.1.2.tgz
    version: 0.1.2
  vxtest:
  - annotations:
      managed-by: ncr
    apiVersion: v2
    appVersion: 0.1.4
    created: "2024-03-26T13:17:31.699492402-04:00"
    description: vxTest Helm chart for test pod
    digest: 342d031f3a24fadfb48e38ebf8fa8425c46601d12d3880d53cf5ba29bbaf2d48
    name: vxtest
    type: application
    urls:
    - docs/vxtest-0.1.4.tgz
    version: 0.1.4
  - annotations:
      managed-by: ncr
    apiVersion: v2
    appVersion: 0.1.3
    created: "2024-03-26T13:17:31.644743999-04:00"
    description: vxTest Helm chart for test pod
    digest: aae860cf9381d5f52252ca45dd0fe44de01307a74f97ba41c57b0f005b41f755
    name: vxtest
    type: application
    urls:
    - docs/vxtest-0.1.3.tgz
    version: 0.1.3
generated: "2024-03-26T13:17:31.573762957-04:00"
