apiVersion: v1
kind: Service
metadata:
  name: simpumps-opt-service
spec:
  selector:
    app: simpumps
  ports:
    - name: wayneix-opt-1-server
      protocol: TCP
      port: 5150
      targetPort: 5150
    - name: wayneix-opt-2-server
      protocol: TCP
      port: 5151
      targetPort: 5151

      