apiVersion: v1
kind: Service
metadata:
  name: simpumps-opt-service
spec:
  selector:
    app: simpumps
  ports:
    - protocol: TCP
      port: 5150
      targetPort: 5150
    - protocol: TCP
      port: 5151
      targetPort: 5151

      