---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vxfuel-deployment
  labels:
    app: vxfuel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vxfuel
  template:
    metadata:
      labels:
        app: vxfuel
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/vxfuel-fluentbit-config.yaml") . | sha256sum }}
    spec:
      hostname: panther2
      volumes:
      - name: vxfuel-persist
        persistentVolumeClaim:
          claimName: vxfuel-persist-claim
      # Fluentbit config files will be mapped here from configmap yaml
      - name: vxfuel-fluentbit-config
        configMap:
          name: vxfuel-fluentbit-config
      initContainers:
      # Sidecar Init container to initialize environment, e.g. create subfolders on mounted volume.
      - name: vxfuel-init
        image: {{ .Values.global.repository }}/vxfuel-init:0.1.4
        volumeMounts:
        - name: vxfuel-persist
          mountPath: "/persist/"
      containers:
      # Sidecar Fluentbit container for log scraping
      - name: vxfuel-fluentbit
        image: cr.fluentbit.io/fluent/fluent-bit:2.2.2
        volumeMounts:
        - name: vxfuel-persist
          mountPath: "/persist/"
        - name: vxfuel-fluentbit-config
          mountPath: /fluent-bit/etc/
        ports:
        - containerPort: 8089
          name: metrics
      - name: vxfuel
        image: {{ .Values.global.repository }}/vxfuel:{{ .Values.global.imageVersion }}
        command:
        - "/usr/bin/tini"
        args:
        - "--"
        - "/opt/config/docker-configure-run.sh"
        volumeMounts:
        - name: vxfuel-persist
          mountPath: "/persist/"
        env:
        - name: USER
          value: pcrfuel
        - name: PATH
          value: "/usr/local/bin:/usr/bin:/bin:/opt/cxoffice/bin:/sbin:/usr/sbin"
        ports:
        - containerPort: 1883
        - containerPort: 9001
        - containerPort: 5901
      imagePullSecrets:
      - name: edge-docker-pull-secret
