---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vxtest-deployment
  labels:
    app: vxtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vxtest
  template:
    metadata:
      labels:
        app: vxtest
    spec:
      hostname: testhost
      containers:
      - name: vxtest
        image: us-east1-docker.pkg.dev/ret-edge-pltf-infra/workloads/vxtest:0.1.6
        env:
        - name: PATH
          value: "/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin"
      imagePullSecrets:
      - name: edge-docker-pull-secret
